# -*- coding: utf-8 -*-
"""q1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/106E6TEkYznUNRiXrIhbesnWtdNGdAUyB
"""

def swap(x, y):

     if not (isinstance(x, (int, float)) and isinstance(y, (int, float))):
         return

     x, y = y, x

     print(f"Swapped values: x = {x}, y = {y}")

result_1 = swap('apple',10)
print(result_1)
swap(-9,17)