# -*- coding: utf-8 -*-
"""q3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/106E6TEkYznUNRiXrIhbesnWtdNGdAUyB
"""

def update_dictionary(dct, key, value):

    if key in dct:
        print(f"Key '{key}' already exists with value: {dct[key]}")

    dct[key] = value
    return dct


print(update_dictionary({}, "name", "Alice"))
print(update_dictionary({"age": 25}, "age", 26))