# -*- coding: utf-8 -*-
"""q5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/106E6TEkYznUNRiXrIhbesnWtdNGdAUyB
"""

def check_divisibility(num, divisor):

    if not (isinstance(num, (int, float)) and isinstance(divisor, (int, float))):
        raise ValueError("Both num and divisor must be numeric.")

    if divisor == 0:
        raise ZeroDivisionError("Divisor cannot be zero.")

    return num % divisor == 0

print(check_divisibility(10, 2))
print(check_divisibility(7, 3))